# Generated by Django 5.2.5 on 2025-08-18 10:37

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_weightlog_timestamp_dailymeallog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailymeallog",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="dailymeallog",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="symptomlog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="weightlog",
            name="timestamp",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="weightlog",
            name="weight_kg",
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name="dailymeallog",
            unique_together={("user", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="weightlog",
            unique_together={("user", "timestamp")},
        ),
    ]
