# Generated by Django 5.2.5 on 2025-08-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "medicine_name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("medicine_type", models.CharField(max_length=50)),
                ("treats_disease", models.CharField(db_index=True, max_length=255)),
                ("frequency", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "meal_relation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("routine", models.TextField(blank=True, null=True)),
                ("side_effects", models.TextField(blank=True, null=True)),
                ("contraindications", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
